name: Release datrie wheels for Windows

on:
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # 下载子模块

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BUILD: "cp311*"
          CIBW_SKIP: "cp36* cp37* cp38* cp39* cp310* pp*"

      - name: Generate Timestamp
        id: timestamp
        run: echo "TAG_NAME=v$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{env.TAG_NAME}}
          release_name: 'Auto Release - ${{env.TAG_NAME}}'
          body: 'Release notes for v1.0.0'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload each wheel to GitHub Releases (Bash)
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for wheel in wheelhouse/*.whl; do
            echo "Uploading $wheel"
            gh release upload "$TAG_NAME" "$wheel"
          done
