name: Build datrie wheels for Windows

on:
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # 下载子模块

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_SKIP: "cp36* cp37* cp38* cp39* cp310*"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: datrie-windows-wheels
          path: wheelhouse/*.whl
